version: '3.8'
services:
  database:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psicologia
      POSTGRES_DB: cadastro
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    entrypoint: ["/bin/bash", "-c", "ls /docker-entrypoint-initdb.d/* > /dev/null 2>&1 && docker-entrypoint.sh postgres || true"]
    ports:
      - "5432:5432"