version: '3.8'
services:
  database:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psicologia
      POSTGRES_DB: cadastro
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: rodrigoleiroz.uerj@gmail.com
      PGADMIN_DEFAULT_PASSWORD: psicologia123
    ports:
      - "5050:80"
    depends_on:
      - database